config/routes.rb
Changayi::Application.routes.draw do
  get "pages/index"

  get "pages/research"

  get "pages/reviews"

  get "pages/about"

  get "pages/help"

  get "pages/terms"

  get "pages/contact"

  get "sessions/new"
  
  resources :vehicles

  resources :users do
	resources :contacts
  end
  
  resources :sessions
  
  match '/signup',  :to => 'users#new'
  match '/buy',  :to => 'vehicles#index'
  match '/sell',  :to => 'vehicles#new'
  match '/login', :to => 'sessions#new'
  match '/research', :to => 'pages#research'
  match '/reviews', :to => 'pages#reviews'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/terms', :to => 'pages#terms'
  match '/contact', :to => 'pages#contact'
  match '/user/update', :to => 'users#edit'

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "accounts" => "users#show", :as => "accounts"
get "search" => "vehicles#find", :as => "search"
get "edit_user" => "users#edit", :as => "update"
	

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
has_one :contact

attr_accessible :name, :email, :password, :password_confirmation
attr_accessor :password
attr_protected :id, :salt
before_save :encrypt_password

email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :name, :presence => true,	:length   => {:minimium => 3, :maximum => 50 }
validates :email, :presence => true, :length   => {:minimium => 3, :maximum => 50 }, :format   => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
validates :password, :presence => true, :length   => {:minimium => 3, :maximum => 10 }, :confirmation => true
validates :password_confirmation, :presence => true, :length   => {:minimium => 3, :maximum => 10 }

def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
end
  
def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.hashed_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
  
def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end
  
 def self.random_string(len)
   #generate a random password consisting of strings and digits
   chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
   newpass = ""
   1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
   return newpass
 end
 
 def send_new_password
  new_pass = User.random_string(10)
  self.password = self.password_confirmation = new_pass
  self.save
  Notifications.deliver_forgot_password(self.email, new_pass)
end

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	
	def login_required
	redirect_to('/login') if current_user.blank?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def research
  end

  def reviews
  end

  def about
  end

  def help
  end

  def terms
  end

  def contact
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :login_required, :only => [:show,:edit,:update]
	
  # GET /users
  # GET /users.json
  def index
	@title = "Home"
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  
  def show
    @user = User.find(current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
	@title = "Sign Up"
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(current_user)
  end
  
  # GET /users/1/edit
  def login
    @title = "login"

    respond_to do |format|
      format.html # login.html.erb
    end
  end
  

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
	respond_to do |format|
    if @user.save	
        session[:user_id] = @user.id
		format.html { redirect_to root_url, notice: 'User was successfully updated.' }
      else
        format.html { render action: "new" }
      end
	end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(current_user)
      if @user.update
        format.html { redirect_to accounts_path, notice: 'User was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(session[:user_id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end


  # GET /vehicles/new
  # GET /vehicles/new.json
  def new
    @vehicle = Vehicle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(params[:vehicle])

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Changayi"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_footer.html.erb
<ul>
	<li><%= link_to "About" %></li>
	<li><%= link_to "Help" %></li>
	<li><%= link_to "Terms of Use" %></li>
	<li><%= link_to "Contact Us" %></li>
</ul>

app/views/layouts/_header.html.erb
	<div class="span-4" id="logo">
			<h1>
				<a title="Changayi nannayal kannadi venda" href="/">changayi</a>
			</h1>
	</div>
	<div class="span-14"  id="header_nav">
		<ul>
			<li><%= link_to "Find Car", '/buy' %></li>
			<li><%= link_to "Find Bike", '/buy' %></li>
			<li><%= link_to "Sell", '/sell' %></li>
			<li><%= link_to "Reviews", '/reviews' %></li>
			<li><%= link_to "Research", '/research' %></li>	
		</ul>
	</div>
	<div class="span-6 last" id="account_links">
		<ul>
			<% if current_user %>
				<li><%= link_to "Sign Out", log_out_path %></li>
				<li><%=link_to current_user.name, accounts_path %></li>
			<% else %>
				<li><%= link_to "Sign up", sign_up_path %></li>
				<li><%= link_to "Sign In", log_in_path %></li>
			<% end %>
		</ul>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= title %></title>
	<%= stylesheet_link_tag 'application'%>
	<!--[if lt IE 8]>
		<%= stylesheet_link_tag 'ie' %>
	<![endif]-->
	
	<%= csrf_meta_tags %>
</head>
<body>
	<div id="main">
	<div id="main_header">
		<div class="container grid">
			<div class="span-24" id="header_container ">
				<%= render 'layouts/header' %>
			</div>
		</div>
	</div>
	<div id="main_content">
		<div class="container">
			<div class="span-24" id="container_content">
				<%= yield %>
			</div>
		</div>
	</div>
	<div id="main_footer">
		<div class="container">
			<div class="span-24" id="footer_links">
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</div>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/index.html.erb
<div class="span-6">
	<div id="box">
		<h3>Find your Car</h3>
		<div id="search">
			<%= form_tag("/search", :method => "get") do %>
			<%= label_tag(:q, "Search for:") %>
			<%= text_field_tag(:q) %>
			<%= submit_tag "Search", :class=>"button" %>
			<% end %>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</div>
</div>
<div class="span-13" id="box">
	<h2>New in the Market</h2>
		<div class="span-13 last" id="news_item_box">
			<div  class="span-5 gallerycontainer">
				<a class="thumbnail" href="#thumb"><img src="assets/2012-Toyota-Camry.jpg" width="90%" border="0" /><span><img src="assets/2012-Toyota-Camry.jpg" width="440px"/><br />Camry 2012</span></a>
			</div>
			<div class="span-8 last">
				<h3>Toyota Camry 2012</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
			</div>
		</div>
		<div class="span-13 last" id="news_item_box">
			<div  class="span-5 gallerycontainer">
				<a class="thumbnail" href="#thumb"><img src="assets/2012-Nissan-Altima.jpg" width="90%" border="0" /><span><img src="assets/2012-Nissan-Altima.jpg" width="440px"/><br />Nissan Altima 2012</span></a>
			</div>
			<div class="span-8 last">
				<h3>Nissan Altima 2012</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
			</div>
		</div>
		
		<div class="span-13 last" id="news_item_box">
			<div  class="span-5 gallerycontainer">
				<a class="thumbnail" href="#thumb"><img src="assets/2012-Nissan-Leaf.jpg" width="90%" border="0" /><span><img src="assets/2012-Nissan-Leaf.jpg" width="440px"/><br />Nissan Leaf 2012</span></a>
			</div>
			<div class="span-8 last">
				<h3>Nissan Leaf 2012</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
			</div>
		</div>
		<div class="span-13 last" id="news_item_box">
			<div  class="span-5 gallerycontainer">
				<a class="thumbnail" href="#thumb"><img src="assets/2012-Toyota-Sienna.jpg" width="90%" border="0" /><span><img src="assets/2012-Toyota-Sienna.jpg" width="440px"/><br />Toyota Sienna 2012</span></a>
			</div>
			<div class="span-8 last">
				<h3>Toyota Sienna 2012</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
			</div>
		</div>
</div>
<div class="span-4 last" id="box">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>

app/views/pages/research.html.erb
<h1>Pages#research</h1>
<p>Find me in app/views/pages/research.html.erb</p>

app/views/pages/reviews.html.erb
<h1>Pages#reviews</h1>
<p>Find me in app/views/pages/reviews.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/users/_form.html.erb
<div class="span-11 push-6" id="box">
	<%= form_for @user do |f| %>

		<fieldset class="inputs">
			<ol>
			<li>
				<div class="span-4"><%= f.label :name %></div>
				<div class="span-5 last"><%= f.text_field :name %></div>
			</li>
			
			<li>
				<div class="span-4"><%= f.label :email %></div>
				<div class="span-5 last"><%= f.text_field :email %></div>
			</li>
			<li>
				<div class="span-4"><%= f.label :password %></div>
				<div class="span-5 last"><%= f.password_field :password %></div>
			</li>
			<li>
				<div class="span-4"><%= f.label :password_confirmation %></div>
				<div class="span-5 last"><%= f.password_field :password_confirmation %></div>
			</li>
				

			<% if @user.errors.any? %>
				<div class="span-6 push-4" id="error_explanation">
				<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
				</div>
			<% end %>
			<li>
				<div class="span-4 push-4 prepend-top"><%= f.submit %></div>		
			</li>
			</ol>
		</fieldset>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Hashed password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.hashed_password %></td>
    <td><%= user.salt %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<div id="content">
	<div class="content_header">
		<h3>Sign up to become a changayi</h3>
	</div>
	<div class="content_left">
	
	</div>
	<div class="content_Signup">	
					<%= render 'form' %>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b> <%= @user.email %>
</p>

<%= button_to 'Edit', '/user/update' %>

</div>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> Error On page</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="span-15" id="box">
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :mileage %><br />
    <%= f.number_field :mileage %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br />
    <%= f.text_field :sale_price %>
  </div>
  <div class="field">
    <%= f.label :photo_URL %><br />
    <%= f.text_field :photo_URL %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br />
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :vehicle_type %><br />
    <%= f.text_field :vehicle_type %>
  </div>
  <div class="field">
    <%= f.label :license_plate %><br />
    <%= f.text_field :license_plate %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br />
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br />
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.number_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<div class="span-8 last" id="box">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<div class="span-7">
	<div id="box">
		<h3>Filter your Search</h3>
		<div id="search">
		Search field here
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
	</div>
</div>

<div class="span-16" id="box">


	<div class="span-16 last result_header">Search Results</div>
	<% @vehicles.each do |vehicle| %>

	<div class="span-16 last" id="news_item_box">

		<div  class="span-7 result_image">
			<td><%= image_tag vehicle.photo_URL,:width => '240' %></td>
		</div>
		<div class="span-8 last">
			<div class="span-8 last result_title">
				<%= vehicle.make %> <%= vehicle.model %> <%= vehicle.style %>
			</div>
			<div class="span-2 result_bold"> Model Year	</div>
			<div class="span-6 last">
				<%= vehicle.year %>
			</div>
			<div class="span-2 result_bold"> Mileage </div>
			<div class="span-6 last">
				<%= vehicle.mileage %>
			</div>
			<div class="span-2 result_bold"> Sale Price	</div>
			<div class="span-6 last">
				<%= vehicle.sale_price %>
			</div>
			<div class="span-2 result_bold"> Details </div>
			<div class="span-6 last">
				<%= vehicle.short_description %>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @vehicle.year %>
</p>

<p>
  <b>Make:</b>
  <%= @vehicle.make %>
</p>

<p>
  <b>Model:</b>
  <%= @vehicle.model %>
</p>

<p>
  <b>Style:</b>
  <%= @vehicle.style %>
</p>

<p>
  <b>Mileage:</b>
  <%= @vehicle.mileage %>
</p>

<p>
  <b>State:</b>
  <%= @vehicle.state %>
</p>

<p>
  <b>City:</b>
  <%= @vehicle.city %>
</p>

<p>
  <b>Sale price:</b>
  <%= @vehicle.sale_price %>
</p>

<p>
  <b>Photo url:</b>
  <%= @vehicle.photo_URL %>
</p>

<p>
  <b>Status:</b>
  <%= @vehicle.status %>
</p>

<p>
  <b>Short description:</b>
  <%= @vehicle.short_description %>
</p>

<p>
  <b>Details:</b>
  <%= @vehicle.details %>
</p>

<p>
  <b>Vehicle type:</b>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <b>License plate:</b>
  <%= @vehicle.license_plate %>
</p>

<p>
  <b>Contact name:</b>
  <%= @vehicle.contact_name %>
</p>

<p>
  <b>Contact phone:</b>
  <%= @vehicle.contact_phone %>
</p>

<p>
  <b>Contact email:</b>
  <%= @vehicle.contact_email %>
</p>

<p>
  <b>Created by:</b>
  <%= @vehicle.created_by %>
</p>


<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>